# Generated by Django 3.0.6 on 2020-10-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('_death_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Death Date')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Undefined', 'Undefined')], max_length=12, null=True)),
                ('skin_color', models.CharField(blank=True, choices=[('pale', 'pale'), ('fair', 'fair'), ('light brown', 'light brown'), ('medium brown', 'medium brown'), ('dark brown', 'dark brown'), ('black', 'black')], max_length=25, null=True, verbose_name='Skin Color')),
                ('hair_color', models.CharField(blank=True, choices=[('blond', 'blond'), ('red', 'red'), ('brown', 'brown'), ('black', 'black')], help_text='Natural color only', max_length=25, null=True, verbose_name='Hair Color')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Undefined', 'Undefined')], max_length=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
