# Generated by Django 3.0.6 on 2020-10-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
