# Generated by Django 3.0.6 on 2020-10-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_professional_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='register',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Professional Register'),
        ),
        migrations.AddField(
            model_name='professional',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='subspecialty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='profession',
            field=models.CharField(blank=True, choices=[('medical doctor', 'medical doctor'), ('nurse', 'nurse'), ('psychologist', 'psychologist')], max_length=50, null=True, verbose_name='Profession'),
        ),
    ]
