# Generated by Django 3.0.6 on 2020-10-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201001_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='aditional_info',
            field=models.TextField(default='', help_text='Please describe additional specialty or titles and press ENTER/RETURN to compose in separate lines', verbose_name='Aditional Info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professional',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Specialty'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='subspecialty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subspecialty'),
        ),
    ]
