# Generated by Django 3.0.6 on 2020-10-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201001_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='English Name')),
                ('pt_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Portuguese Name')),
                ('es_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spanish Name')),
                ('_search_names', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'ordering': ['pt_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='English Name')),
                ('pt_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Portuguese Name')),
                ('es_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spanish Name')),
                ('_search_names', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('abrev', models.CharField(max_length=3, verbose_name='Nation Abreviation')),
            ],
            options={
                'ordering': ['pt_name'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='professional',
            options={'verbose_name': 'Professional', 'verbose_name_plural': 'Professionals'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='main_phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='other_phone',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='main_phone',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='other_phone',
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='English Name')),
                ('pt_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Portuguese Name')),
                ('es_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spanish Name')),
                ('_search_names', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('abrev', models.CharField(max_length=2, verbose_name='Region Abreviation')),
                ('nation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Nation')),
            ],
            options={
                'ordering': ['pt_name'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='nation',
            constraint=models.UniqueConstraint(fields=('pt_name',), name='unique_nation'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Region'),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.City'),
        ),
        migrations.AddField(
            model_name='professional',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.City'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('pt_name',), name='unique_region'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('pt_name',), name='unique_city'),
        ),
    ]
