# Generated by Django 3.0.6 on 2020-10-01 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20201001_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='nation',
            options={'verbose_name': 'Nation', 'verbose_name_plural': 'Nations'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.RemoveConstraint(
            model_name='city',
            name='unique_city',
        ),
        migrations.RemoveConstraint(
            model_name='nation',
            name='unique_nation',
        ),
        migrations.RemoveConstraint(
            model_name='region',
            name='unique_region',
        ),
        migrations.AddField(
            model_name='patient',
            name='_is_ongoing',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='_is_protected',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date and Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time'),
        ),
        migrations.AddField(
            model_name='professional',
            name='_is_ongoing',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='professional',
            name='_is_protected',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='professional',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date and Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time'),
        ),
    ]
