# Generated by Django 3.0.6 on 2020-10-01 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20201001_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Professional')),
            ],
        ),
    ]
