# Generated by Django 3.0.6 on 2020-10-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20201003_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='_is_active',
            new_name='_is_person_active',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='_is_active',
            new_name='_is_person_active',
        ),
        migrations.AddField(
            model_name='patient',
            name='_search_names',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='_search_names',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
