# Generated by Django 3.0.6 on 2020-10-03 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_auto_20201003_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='_search_names',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='_search_names',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
