# Generated by Django 3.0.6 on 2020-10-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20201003_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='patients',
            field=models.ManyToManyField(related_name='enterprise_patients', to='base.Patient'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='professionals',
            field=models.ManyToManyField(related_name='enterprise_professionals', to='base.Patient'),
        ),
    ]
