# Generated by Django 3.0.6 on 2020-10-03 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0015_auto_20201003_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('_is_ongoing', models.BooleanField(default=True, editable=False)),
                ('_is_protected', models.BooleanField(default=False, editable=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('_is_person_active', models.BooleanField(default=True, editable=False)),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Undefined', 'Undefined')], max_length=12, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('neiborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Neiborhood')),
                ('main_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone (main)')),
                ('other_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone (other)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.City')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'permissions': [('inactivate_employee', 'Can inactivate the professional.'), ('can_be_assistant', 'Can assist professional.')],
            },
        ),
    ]
