# Generated by Django 3.0.6 on 2020-10-03 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0016_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.CreateModel(
            name='ComercialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.ManyToManyField(blank=True, related_name='comercialuser_employees', to='base.Employee')),
                ('enterprises', models.ManyToManyField(blank=True, related_name='comercialuser_enterprises', to='base.Enterprise')),
                ('professionals', models.ManyToManyField(blank=True, related_name='comercialuser_professionals', to='base.Professional')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
