# Generated by Django 3.0.6 on 2020-10-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20201003_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comercialuser',
            options={'verbose_name': 'Comercial User', 'verbose_name_plural': 'Comercial Users'},
        ),
        migrations.AddField(
            model_name='comercialuser',
            name='_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comercialuser',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
