# Generated by Django 3.0.6 on 2020-10-03 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20201003_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ComercialUser'),
        ),
    ]
