# Generated by Django 3.0.6 on 2020-10-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='start_hour',
            field=models.IntegerField(choices=[('0 h', 0), ('1 h', 3600), ('2 h', 7200), ('3 h', 10800), ('4 h', 14400), ('5 h', 18000), ('6 h', 21600), ('7 h', 25200), ('8 h', 28800), ('9 h', 32400), ('10 h', 36000), ('11 h', 39600), ('12 h', 43200), ('13 h', 46800), ('14 h', 50400), ('15 h', 54000), ('16 h', 57600), ('17 h', 61200), ('18 h', 64800), ('19 h', 68400), ('20 h', 72000), ('21 h', 75600), ('22 h', 79200), ('23 h', 82800)], default=3600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(choices=[(900, '15 MIN'), (1800, '30 MIN'), (2700, '45 MIN'), (3600, '60 MIN'), (5400, '90 MIN'), (7200, '120 MIN'), (9000, '150 MIN')], default=2700),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.DateField(),
        ),
    ]
