# Generated by Django 3.0.6 on 2020-10-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20201003_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='start_hour',
            field=models.IntegerField(choices=[(0, '0h'), (3600, '1h'), (7200, '2h'), (10800, '3h'), (14400, '4h'), (18000, '5h'), (21600, '6h'), (25200, '7h'), (28800, '8h'), (32400, '9h'), (36000, '10h'), (39600, '11h'), (43200, '12h'), (46800, '13h'), (50400, '14h'), (54000, '15h'), (57600, '16h'), (61200, '17h'), (64800, '18h'), (68400, '19h'), (72000, '20h'), (75600, '21h'), (79200, '22h'), (82800, '23h')]),
        ),
    ]
