# Generated by Django 3.0.6 on 2020-10-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20201003_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='min_duration',
            field=models.IntegerField(choices=[(60, '1min'), (360, '6min'), (660, '11min'), (960, '16min'), (1260, '21min'), (1560, '26min'), (1860, '31min'), (2160, '36min'), (2460, '41min'), (2760, '46min'), (3060, '51min'), (3360, '56min')], default=60),
            preserve_default=False,
        ),
    ]
