# Generated by Django 3.0.6 on 2020-10-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_schedule_min_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='start',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='start_hour',
            new_name='hour',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='min_duration',
        ),
        migrations.AddField(
            model_name='schedule',
            name='min',
            field=models.IntegerField(choices=[(300, '5min'), (600, '10min'), (900, '15min'), (1200, '20min'), (1500, '25min'), (1800, '30min'), (2100, '35min'), (2400, '40min'), (2700, '45min'), (3000, '50min'), (3300, '55min')], default=3600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(choices=[(900, '15min'), (1800, '30min'), (2700, '45min'), (3600, '60min'), (4500, '75min'), (5400, '90min'), (6300, '105min')]),
        ),
    ]
