# Generated by Django 3.0.6 on 2020-10-04 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20201003_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Relation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(choices=[(15, '15min'), (30, '30min'), (45, '45min'), (60, '60min'), (75, '75min'), (90, '90min'), (105, '105min'), (120, '120min')], default=60),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hour',
            field=models.IntegerField(choices=[(0, '0h'), (1, '1h'), (2, '2h'), (3, '3h'), (4, '4h'), (5, '5h'), (6, '6h'), (7, '7h'), (8, '8h'), (9, '9h'), (10, '10h'), (11, '11h'), (12, '12h'), (13, '13h'), (14, '14h'), (15, '15h'), (16, '16h'), (17, '17h'), (18, '18h'), (19, '19h'), (20, '20h'), (21, '21h'), (22, '22h'), (23, '23h')], default=8),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='min',
            field=models.IntegerField(choices=[(0, '0min'), (5, '5min'), (10, '10min'), (15, '15min'), (20, '20min'), (25, '25min'), (30, '30min'), (35, '35min'), (40, '40min'), (45, '45min'), (50, '50min'), (55, '55min')], default=60),
        ),
    ]
