# Generated by Django 3.0.6 on 2020-10-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20201003_2233'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comercialuser',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_comercial_user'),
        ),
    ]
