# Generated by Django 3.0.6 on 2020-10-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20201008_2129'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('user', 'first_name', 'last_name', 'birth_date', 'gender'), name='unique_patient'),
        ),
        migrations.AddConstraint(
            model_name='professional',
            constraint=models.UniqueConstraint(fields=('user', 'first_name', 'last_name', 'birth_date', 'gender'), name='unique_professional'),
        ),
    ]
