# Generated by Django 3.0.6 on 2020-10-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20201008_2135'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relation',
            constraint=models.UniqueConstraint(fields=('patient', 'professional'), name='unique_relation'),
        ),
    ]
