# Generated by Django 3.0.6 on 2020-10-11 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20201011_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='relation',
        ),
        migrations.AddField(
            model_name='schedule',
            name='professional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Professional'),
            preserve_default=False,
        ),
    ]
