# Generated by Django 3.0.6 on 2020-10-14 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_schedule_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(choices=[(15, '15 min'), (30, '30 min'), (45, '45 min'), (60, '60 min'), (75, '75 min'), (90, '90 min'), (105, '105 min'), (120, '120 min')], default=60),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hour',
            field=models.IntegerField(choices=[(0, '0 h'), (1, '1 h'), (2, '2 h'), (3, '3 h'), (4, '4 h'), (5, '5 h'), (6, '6 h'), (7, '7 h'), (8, '8 h'), (9, '9 h'), (10, '10 h'), (11, '11 h'), (12, '12 h'), (13, '13 h'), (14, '14 h'), (15, '15 h'), (16, '16 h'), (17, '17 h'), (18, '18 h'), (19, '19 h'), (20, '20 h'), (21, '21 h'), (22, '22 h'), (23, '23 h')], default=8),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='min',
            field=models.IntegerField(choices=[(0, '0 min'), (15, '15 min'), (30, '30 min'), (45, '45 min')], default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Professional'),
        ),
    ]
