# Generated by Django 3.0.6 on 2020-10-19 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20201014_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='English Name')),
                ('pt_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Portuguese Name')),
                ('es_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spanish Name')),
                ('_search_names', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'ordering': ['pt_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='English Name')),
                ('pt_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Portuguese Name')),
                ('es_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spanish Name')),
                ('_search_names', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'ordering': ['pt_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='English Name')),
                ('pt_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Portuguese Name')),
                ('es_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spanish Name')),
                ('_search_names', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'ordering': ['pt_name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='relation',
            name='_is_ongoing',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='relation',
            name='_is_protected',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='relation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date and Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time'),
        ),
        migrations.AddField(
            model_name='relation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='symptom',
            constraint=models.UniqueConstraint(fields=('pt_name',), name='unique_symptom'),
        ),
        migrations.AddField(
            model_name='structure',
            name='symptoms',
            field=models.ManyToManyField(blank=True, related_name='structure_symptoms', to='base.Symptom'),
        ),
        migrations.AddField(
            model_name='organ',
            name='structures',
            field=models.ManyToManyField(blank=True, related_name='organ_structures', to='base.Structure'),
        ),
        migrations.AddConstraint(
            model_name='structure',
            constraint=models.UniqueConstraint(fields=('pt_name',), name='unique_structure'),
        ),
        migrations.AddConstraint(
            model_name='organ',
            constraint=models.UniqueConstraint(fields=('pt_name',), name='unique_organ'),
        ),
    ]
