# Generated by Django 3.0.6 on 2020-10-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20201019_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(choices=[(15, '15 h'), (30, '30 h'), (45, '45 h'), (60, '60 h'), (75, '75 h'), (90, '90 h'), (105, '105 h'), (120, '120 h')], default=60),
        ),
    ]
