# Generated by Django 3.0.6 on 2020-10-05 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCompound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='English Name')),
                ('pt_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Portuguese Name')),
                ('es_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spanish Name')),
                ('_search_names', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompoundSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='English Name')),
                ('pt_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Portuguese Name')),
                ('es_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spanish Name')),
                ('_search_names', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('active_compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meds.ActiveCompound')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComercialDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='English Name')),
                ('pt_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Portuguese Name')),
                ('es_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spanish Name')),
                ('_search_names', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('compound_sets', models.ManyToManyField(related_name='comercialdrug_compound_sets', to='meds.CompoundSet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
