# Generated by Django 3.0.6 on 2020-10-05 01:16

import Laelia.apps.base.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compoundset',
            name='_search_names',
        ),
        migrations.RemoveField(
            model_name='compoundset',
            name='en_name',
        ),
        migrations.RemoveField(
            model_name='compoundset',
            name='es_name',
        ),
        migrations.RemoveField(
            model_name='compoundset',
            name='pt_name',
        ),
        migrations.AddField(
            model_name='compoundset',
            name='strength_measure_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='compoundset',
            name='strength_value',
            field=Laelia.apps.base.fields.MinMaxFloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compoundset',
            name='active_compound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meds.ActiveCompound'),
        ),
    ]
