# Generated by Django 3.0.6 on 2020-10-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0002_auto_20201004_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercialdrug',
            name='unit_measure_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comercialdrug',
            name='unit_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comercialdrug',
            name='units_per_box',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
