# Generated by Django 3.0.6 on 2020-10-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0003_auto_20201004_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comercialdrug',
            old_name='units_per_box',
            new_name='box_content',
        ),
        migrations.RenameField(
            model_name='comercialdrug',
            old_name='unit_measure_unit',
            new_name='dosage_form',
        ),
        migrations.RemoveField(
            model_name='comercialdrug',
            name='unit_value',
        ),
        migrations.AddField(
            model_name='comercialdrug',
            name='presentation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
