# Generated by Django 3.0.6 on 2020-10-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0005_auto_20201004_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercialdrug',
            name='_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
