# Generated by Django 3.0.6 on 2020-10-05 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0006_comercialdrug__name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrescriptionMixin',
            new_name='Prescription',
        ),
    ]
