# Generated by Django 3.0.6 on 2020-10-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0007_auto_20201005_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dosage_regimen',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='dose',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Days treatment duration. Keep blank for continuous', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'daily'), (7, 'weekly'), (14, 'biweekly'), (30, 'month')], default=1),
        ),
    ]
