# Generated by Django 3.0.6 on 2020-10-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0009_auto_20201005_0633'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activecompound',
            constraint=models.UniqueConstraint(fields=('pt_name',), name='unique_activecompound'),
        ),
    ]
