# Generated by Django 3.0.6 on 2020-10-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0010_auto_20201005_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comercialdrug',
            options={'ordering': ['pt_name']},
        ),
    ]
