# Generated by Django 3.0.6 on 2020-10-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0014_auto_20201010_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
