# Generated by Django 3.0.6 on 2020-10-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0017_prescription_boxes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comercialdrug',
            name='unique_comercialdrug',
        ),
        migrations.AddConstraint(
            model_name='comercialdrug',
            constraint=models.UniqueConstraint(fields=('pt_name', 'total_content', 'volumes'), name='unique_comercialdrug'),
        ),
    ]
