# Generated by Django 3.0.6 on 2020-10-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0018_auto_20201010_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercialdrug',
            name='total_content',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
    ]
