# Generated by Django 3.0.6 on 2020-10-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0019_auto_20201010_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercialdrug',
            name='total_content',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
    ]
