# Generated by Django 3.0.6 on 2020-10-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0020_auto_20201010_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dose',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
