# Generated by Django 3.0.6 on 2020-10-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0021_auto_20201010_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dosage_regimen',
            field=models.IntegerField(blank=True, choices=[(1, '1x'), (2, '2x'), (3, '3x'), (4, '4x'), (5, '5x'), (6, '6x'), (7, '7x'), (8, '8x'), (9, '9x'), (10, '10x'), (11, '11x'), (12, '12x')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
