# Generated by Django 3.0.6 on 2020-10-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0022_auto_20201017_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveConstraint(
            model_name='prescription',
            name='unique_prescription',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(fields=('comercial_drug', 'relation', 'start_date'), name='unique_prescription'),
        ),
    ]
