# Generated by Django 3.0.6 on 2020-10-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_medicallicence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicallicence',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='medicallicence',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='medicallicence',
            name='to_time',
        ),
    ]
