# Generated by Django 3.0.6 on 2020-10-01 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_relation'),
        ('care', '0002_timelineevent_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Relation'),
        ),
    ]
