# Generated by Django 3.0.6 on 2020-10-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_auto_20201001_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(blank=True, choices=[('trauma', 'trauma'), ('disease', 'disease'), ('positive mark', 'positive mark'), ('negative mark', 'negative mark')], max_length=50, null=True),
        ),
    ]
