# Generated by Django 3.0.6 on 2020-10-22 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_auto_20201022_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicallicence',
            name='reference_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='care.Visit'),
        ),
    ]
