# Generated by Django 3.0.6 on 2020-10-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_medicallicence_reference_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='urgency',
            field=models.BooleanField(default=False),
        ),
    ]
