# Generated by Django 3.0.6 on 2020-10-02 05:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_auto_20201002_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
