# Generated by Django 3.0.6 on 2020-10-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_visit_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='complaint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
