# Generated by Django 3.0.6 on 2020-10-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_visit_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='new_complaint',
            field=models.BooleanField(default=False),
        ),
    ]
