# Generated by Django 3.0.6 on 2020-10-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_auto_20201002_0513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeLineEvent',
        ),
    ]
