# Generated by Django 3.0.6 on 2020-10-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0007_visit_new_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='new_complaint',
            field=models.BooleanField(default=False, verbose_name='New?'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='urgency',
            field=models.BooleanField(default=False, verbose_name='Acute?'),
        ),
    ]
