# Generated by Django 3.0.6 on 2020-10-02 05:25

import Laelia.apps.base.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0010_relation'),
        ('care', '0007_delete_timelineevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_at_event', Laelia.apps.base.fields.MinMaxFloatField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('event_type', models.CharField(blank=True, choices=[('trauma', 'trauma'), ('disease', 'disease'), ('positive mark', 'positive mark'), ('negative mark', 'negative mark')], max_length=50, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Relation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
