# Generated by Django 3.0.6 on 2020-10-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20201003_2233'),
        ('care', '0008_timelineevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeLineEvent',
            new_name='Event',
        ),
    ]
