# Generated by Django 3.0.6 on 2020-10-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0009_auto_20201004_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visit_type',
            field=models.CharField(blank=True, choices=[('first visit', 'first visit'), ('follow up', 'follow up'), ('new complaint', 'new complaint'), ('revisit', 'revisit')], max_length=50, null=True),
        ),
    ]
