# Generated by Django 3.0.6 on 2020-10-05 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0010_event_visit_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['age_at_event']},
        ),
        migrations.AddField(
            model_name='event',
            name='_is_ongoing',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='_is_protected',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date and Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time'),
        ),
    ]
