# Generated by Django 3.0.6 on 2020-10-05 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0011_auto_20201004_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['age_at_event', 'created']},
        ),
    ]
